# Docker Compose spec for running Pi-hole and Unbound in recursive mode
# by @jareddantis, 2023
#
# Base path: /etc/docker/compose/pihole-unbound
# Required paths:
#   - pihole/, unbound/, dnsmasq.d/
#     > just create empty directories
#   - unbound/unbound.conf, root.hints
#     > see https://docs.pi-hole.net/guides/dns/unbound/
#     > save the pi-hole.conf file as unbound.conf
#
# Notes:
#   1. This creates a network on the subnet 192.168.1.0/24. If this conflicts
#      with your network, change the subnet, gateway, and IP addresses accordingly.
#   2. The orbital-sync container is configured for syncing with other Pi-hole instances
#      over Tailscale. Feel free to remove the service if this does not apply to you.

version: '3'

services:
  unbound:
    container_name: unbound
    image: mvance/unbound:latest
    ports:
      - "5335:53/tcp"
      - "5335:53/udp"
    volumes:
      - /etc/docker/compose/pihole-unbound/unbound/unbound.conf:/opt/unbound/etc/unbound/unbound.conf
      - /etc/docker/compose/pihole-unbound/unbound/root.hints:/opt/unbound/etc/unbound/root.hints
      - /var/log/unbound.log:/opt/unbound/etc/unbound/unbound.log
    restart: unless-stopped
    networks:
      pihole_net:
        ipv4_address: 192.168.1.2
  pihole:
    hostname: dantis
    container_name: pihole
    image: pihole/pihole:latest
    depends_on:
      unbound:
        condition: service_healthy
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "10000:80/tcp"
    environment:
      TZ: 'Asia/Manila'
      WEBPASSWORD: '*************'
      PIHOLE_DNS_: '192.168.1.2#53'
      DNSSEC: 'true'
      FTLCONF_LOCAL_IPV4: '172.16.0.252'
    volumes:
      - /etc/docker/compose/pihole-unbound/pihole:/etc/pihole
      - /etc/docker/compose/pihole-unbound/dnsmasq.d:/etc/dnsmasq.d
      # - /sys/class/thermal/thermal_zone1/temp:/sys/class/thermal/thermal_zone0/temp:ro
    restart: unless-stopped
    networks:
      pihole_net:
        ipv4_address: 192.168.1.3
  orbital-sync:
    container_name: orbital-sync
    image: mattwebbio/orbital-sync:1
    depends_on:
      pihole:
        condition: service_healthy
    environment:
      PRIMARY_HOST_BASE_URL: 'http://192.168.1.3'
      PRIMARY_HOST_PASSWORD: '***************'
      SECONDARY_HOST_1_BASE_URL: 'http://rpi.bleak-bangus.ts.net'      # Tailscale
      SECONDARY_HOST_1_PASSWORD: '***************'
      INTERVAL_MINUTES: 1440
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/resolv.conf:/etc/resolv.conf:ro                           # Tailscale
    restart: unless-stopped
    networks:
      pihole_net:
        ipv4_address: 192.168.1.4

networks:
  pihole_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
